// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBceSYwRgIvYSvNEhz8bx-Ews9r2EsQNBU',
    appId: '1:68148621395:web:33e5b6f19cf1d51e8c56a6',
    messagingSenderId: '68148621395',
    projectId: 'garbage-collector-d114a',
    authDomain: 'garbage-collector-d114a.firebaseapp.com',
    storageBucket: 'garbage-collector-d114a.appspot.com',
    measurementId: 'G-RFSYW7TTEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_OqSgUNNzVeLUAitF4ZtRzH80MmOO4UU',
    appId: '1:68148621395:android:f76ffdb1441a0fb38c56a6',
    messagingSenderId: '68148621395',
    projectId: 'garbage-collector-d114a',
    storageBucket: 'garbage-collector-d114a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0aRVnSiPDAvWl_QenfuycGczysBu_0ZQ',
    appId: '1:68148621395:ios:05ca38290d81654d8c56a6',
    messagingSenderId: '68148621395',
    projectId: 'garbage-collector-d114a',
    storageBucket: 'garbage-collector-d114a.appspot.com',
    iosClientId: '68148621395-0ip7m0o72t2nretm6vclfie71sv9s4h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.garbageCollectorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0aRVnSiPDAvWl_QenfuycGczysBu_0ZQ',
    appId: '1:68148621395:ios:05ca38290d81654d8c56a6',
    messagingSenderId: '68148621395',
    projectId: 'garbage-collector-d114a',
    storageBucket: 'garbage-collector-d114a.appspot.com',
    iosClientId: '68148621395-0ip7m0o72t2nretm6vclfie71sv9s4h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.garbageCollectorApp',
  );
}
