// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDjp0Xjp2xNcjYAeuc3xrA4gNE6DdEyg',
    appId: '1:620853047278:web:8f93ccce14a2f72d0528ff',
    messagingSenderId: '620853047278',
    projectId: 'garbage-collector-app-19376',
    authDomain: 'garbage-collector-app-19376.firebaseapp.com',
    storageBucket: 'garbage-collector-app-19376.appspot.com',
    measurementId: 'G-WEN6SM9MVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9-Po0sVkf0Exp5q-98MCDN1aP6LSSzFA',
    appId: '1:620853047278:android:a8b2393a49bbccc10528ff',
    messagingSenderId: '620853047278',
    projectId: 'garbage-collector-app-19376',
    storageBucket: 'garbage-collector-app-19376.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFu0lX869FhDpf-9UhHuaIK8FyVvkl5zo',
    appId: '1:620853047278:ios:b6687096819136f10528ff',
    messagingSenderId: '620853047278',
    projectId: 'garbage-collector-app-19376',
    storageBucket: 'garbage-collector-app-19376.appspot.com',
    iosClientId: '620853047278-o1idpv7293rfusgtcr43i0fio8mn1sih.apps.googleusercontent.com',
    iosBundleId: 'com.example.garbageCollectorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFu0lX869FhDpf-9UhHuaIK8FyVvkl5zo',
    appId: '1:620853047278:ios:b6687096819136f10528ff',
    messagingSenderId: '620853047278',
    projectId: 'garbage-collector-app-19376',
    storageBucket: 'garbage-collector-app-19376.appspot.com',
    iosClientId: '620853047278-o1idpv7293rfusgtcr43i0fio8mn1sih.apps.googleusercontent.com',
    iosBundleId: 'com.example.garbageCollectorApp',
  );
}
